---
language: python
python: "2.7"

# Install ansible
addons:
  apt:
    packages:
    - python-pip
  ssh_known_hosts:
  - galaxy.ansible.com

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Install the role from GitHub master
  - ansible-galaxy install -r tests/requirements.yml
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # Run the role
  - ansible-playbook tests/test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/